backend:
  name: git-gateway
  branch: main

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Homepage"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - {
              label: Header,
              name: header,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Subheading, name: subheading, widget: string },
                  {
                    label: Headerimage,
                    name: headerimage,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                ],
            }
          - {
              label: Success,
              name: success,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Blurbs,
                    name: blurbs,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Heading, name: heading, widget: string },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Courses,
              name: courses,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Image,
                    name: image,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Details,
                    name: details,
                    widget: list,
                    fields:
                      [
                        { label: Type, name: type, widget: string },
                        { label: Icon, name: icon, widget: image },
                        { label: Heading, name: heading, widget: string },
                        { label: Subheading, name: subheading, widget: string },
                        { label: Prevprice, name: prevprice, widget: string },
                        {
                          label: Currentprice,
                          name: currentprice,
                          widget: string,
                        },
                        { label: Duration, name: duration, widget: string },
                        { label: Conditions, name: conditions, widget: string },
                      ],
                  },
                ],
            }
          - {
              label: Curriculum,
              name: curriculum,
              widget: object,
              fields:
                [
                  { label: Smalltext, name: smalltext, widget: string },
                  { label: Heading, name: heading, widget: string },
                  { label: Subheading, name: subheading, widget: string },
                  {
                    label: Image,
                    name: image,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Instructors,
                    name: instructors,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Name, name: name, widget: string },
                        { label: Position, name: position, widget: string },
                        { label: Experience, name: experience, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Formerstudents,
              name: formerstudents,
              widget: list,
              fields:
                [
                  { label: Image, name: image, widget: image },
                  { label: Testimonial, name: testimonial, widget: text },
                  { label: Studentname, name: studentname, widget: string },
                  { label: Position, name: position, widget: string },
                ],
            }
      - file: src/pages/about/index.md
        label: About
        name: about
        fields:
          - {
              label: Template Key,
              name: templateKey,
              widget: hidden,
              default: about-page,
            }
          - { label: Title, name: title, widget: string }
          - {
              label: Header,
              name: header,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Subheading, name: subheading, widget: string },
                ],
            }
          - {
              label: Image,
              name: image,
              widget: object,
              fields:
                [
                  { label: Alt, name: alt, widget: string },
                  { label: Image, name: image, widget: image },
                ],
            }
          - {
              label: Why,
              name: why,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Reasons,
                    name: reasons,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Heading, name: heading, widget: string },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Rocket,
              name: rocket,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Text, name: text, widget: text },
                  {
                    label: Image,
                    name: image,
                    widget: object,
                    fields:
                      [
                        { label: Alt, name: alt, widget: string },
                        { label: Image, name: image, widget: image },
                      ],
                  },
                  { label: Quote, name: quote, widget: text },
                  { label: Name, name: name, widget: string },
                  { label: Position, name: position, widget: string },
                ],
            }
          - {
              label: Companies,
              name: companies,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Icons,
                    name: icons,
                    widget: list,
                    fields: [{ label: Image, name: image, widget: image }],
                  },
                ],
            }
          - {
              label: Leadership,
              name: leadership,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Profiles,
                    name: profiles,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Name, name: name, widget: string },
                        { label: position, name: position, widget: string },
                      ],
                  },
                ],
            }
      - file: src/pages/faq/index.md
        label: Faq
        name: faq
        fields:
          - {
              label: Template Key,
              name: templateKey,
              widget: hidden,
              default: faq-page,
            }
          - { label: Title, name: title, widget: string }
          - {
              label: Header,
              name: header,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Smalltext, name: smalltext, widget: string },
                ],
            }
          - {
              label: General,
              name: general,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Questions,
                    name: questions,
                    widget: list,
                    fields:
                      [
                        { label: Question, name: question, widget: string },
                        { label: Answers, name: answers, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Codingbasics,
              name: codingbasics,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Questions,
                    name: questions,
                    widget: list,
                    fields:
                      [
                        { label: Question, name: question, widget: string },
                        { label: Answers, name: answers, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Softwareengineeringbootcamp,
              name: softwareengineeringbootcamp,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Questions,
                    name: questions,
                    widget: list,
                    fields:
                      [
                        { label: Question, name: question, widget: string },
                        { label: Answers, name: answers, widget: text },
                      ],
                  },
                ],
            }
      - file: src/pages/basics.md
        label: Basics
        name: basics
        fields:
          - {
              label: Template Key,
              name: templateKey,
              widget: hidden,
              default: basics-page,
            }
          - { label: Title, name: title, widget: string }
          - {
              label: Header,
              name: header,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Subheading, name: subheading, widget: string },
                  {
                    label: Reasons,
                    name: reasons,
                    widget: list,
                    fields: [{ label: Reason, name: reason, widget: string }],
                  },
                ],
            }
          - {
              label: Overview,
              name: overview,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Studentexperience,
                    name: studentexperience,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Heading, name: heading, widget: string },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Testimonial,
              name: testimonial,
              widget: object,
              fields:
                [
                  { label: quote, name: quote, widget: text },
                  { label: Image, name: image, widget: image },
                  { label: Name, name: name, widget: string },
                  { label: Position, name: position, widget: string },
                ],
            }
          - {
              label: Learningstyle,
              name: learningstyle,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Card,
                    name: card,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Heading, name: heading, widget: string },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Technicalknowledge,
              name: technicalknowledge,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Topics,
                    name: topics,
                    widget: list,
                    fields: [{ label: Topic, name: topic, widget: string }],
                  },
                ],
            }
          - {
              label: Instructors,
              name: instructors,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  {
                    label: Profile,
                    name: profile,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Name, name: name, widget: string },
                        { label: Position, name: name, widget: string },
                      ],
                  },
                ],
            }
          - {
              label: Admissions,
              name: admissions,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Subheading, name: subheading, widget: string },
                  { label: Cardheading, name: cardheading, widget: string },
                  { label: Prevcost, name: prevcost, widget: string },
                  { label: Currentcost, name: currentcost, widget: string },
                  {
                    label: Objectives,
                    name: objectives,
                    widget: list,
                    fields:
                      [{ label: Objective, name: objective, widget: string }],
                  },
                ],
            }
          - {
              {
                label: Programdates,
                name: programdates,
                widget: object,
                fields:
                  [
                    { label: Heading, name: heading, widget: string },
                    { label: Subheading, name: subheading, widget: string },
                  ],
              },
            }
          - {
              label: Lessons,
              name: lessons,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Subheading, name: subheading, widget: string },
                  {
                    label: Lesson,
                    name: lesson,
                    widget: list,
                    fields:
                      [
                        { label: Week, name: week, widget: string },
                        { label: Name, name: name, widget: string },
                        { label: Preclass, name: preclass, widget: text },
                        { label: Inclass, name: inclass, widget: text },
                        { label: Project, name: project, widget: text },
                      ],
                  },
                ],
            }
